version: 0.2

phases:
  install:
    commands:
      - echo 'Installing Python dependencies'
      - dnf install -y python3 python3-pip
      - pip3 install --upgrade pip
      - pip3 install pytest

  build:
    commands:
      - echo 'Running all Python tests sequentially'
      - mkdir -p report
      - python3 -m pytest tests/ --junitxml=report/test_report.xml

  post_build:
    commands:
      - echo "Test execution completed"

reports:
  pytest_reports:
    files:
      - "*.xml"
    base-directory: "report"
    file-format: JUNITXML
